#!/usr/bin/env bash
# ./bootstrap-oss-terminal.sh
# Environment setup for QuantumServiceOperationSDNarchitecture

set -eo pipefail

echo "=================================================================="
echo "  Bootstrapping QuantumServiceOperationSDNarchitecture Environment"
echo "=================================================================="

# Print a prompt, read a line, and echo the value (either the user's
# input or the default if the input was empty). Mirrors the helper of
# the same name in the controller and node bootstraps so all three
# scripts behave identically.
prompt_with_default() {
    local prompt_text="$1"
    local default_value="$2"
    local input_value=""
    echo -e -n "${prompt_text} [${default_value}]: " >&2
    read -r input_value || true
    if [ -z "$input_value" ]; then
        echo "$default_value"
    else
        echo "$input_value"
    fi
}

# ---------------------------------------------------------------------------
# Phase -1: Resolve user-configurable deployment values
#
# The operational terminal needs to know where the µONOS controller is and
# which physical node it is talking to. These three values are prompted
# once, persisted to ~/.quantum-sdn/config.env, and reused on subsequent
# runs. They are consumed by:
#   - test-sdn-protocol-switching-performance.sh (both modes)
#   - any charm client that talks to the controller
#   - the RESTCONF path when the gateway is reached via the controller IP
#
# The config file is shared with the controller bootstrap
# (bootstrap-quantum-switching-sdn.sh), so a machine that runs both
# repositories only prompts once. The 172.21.x.x address family matches
# the MANO / 6G-OpenLab convention used everywhere else:
#   - controller / cluster node:  172.21.2.23
#   - quantum node (BeagleBone):  172.21.128.254
#
# Override non-interactively with, for example:
#   CONTROLLER_HOST=192.168.1.10 ./bootstrap-oss-terminal.sh
# ---------------------------------------------------------------------------

QUANTUM_SDN_CONF_DIR="${HOME}/.quantum-sdn"
QUANTUM_SDN_CONF="${QUANTUM_SDN_CONF_DIR}/config.env"

# Defaults (only used if not already set in the shell nor in the config file)
: "${CONTROLLER_HOST:=172.21.2.23}"
: "${QUANTUM_NODE_ID:=quantum-node-1}"
: "${QUANTUM_NODE_IP:=172.21.128.254}"

# Load persisted config. Values in the file are only applied if the shell
# has not already set them, so an env override on the command line wins.
if [ -f "$QUANTUM_SDN_CONF" ]; then
    while IFS='=' read -r k v; do
        case "$k" in ''|\#*) continue ;; esac
        if [ -z "${!k:-}" ]; then
            printf -v "$k" '%s' "$v"
            export "$k"
        fi
    done < "$QUANTUM_SDN_CONF"
fi

# Interactive prompt — only if stdin is a terminal. CI / piped execution
# falls through and uses the defaults above.
if [ -t 0 ]; then
    echo
    echo "==========================================================="
    echo "   Deployment Configuration"
    echo "==========================================================="
    echo "Press ENTER to accept the value in [brackets]."
    echo

    CONTROLLER_HOST=$(prompt_with_default "Enter the IP address of the Network Controller" "$CONTROLLER_HOST")
    QUANTUM_NODE_ID=$(prompt_with_default "Enter the physical node ID (topo entity name)" "$QUANTUM_NODE_ID")
    QUANTUM_NODE_IP=$(prompt_with_default "Enter the physical node IP (BeagleBone address)" "$QUANTUM_NODE_IP")

    echo
fi

export CONTROLLER_HOST QUANTUM_NODE_ID QUANTUM_NODE_IP

# Persist so re-runs are silent.
mkdir -p "$QUANTUM_SDN_CONF_DIR"
chmod 700 "$QUANTUM_SDN_CONF_DIR"
cat > "$QUANTUM_SDN_CONF" <<EOF
# Generated by bootstrap-oss-terminal.sh — safe to delete.
# Delete this file to be re-prompted on the next bootstrap run.
CONTROLLER_HOST=$CONTROLLER_HOST
QUANTUM_NODE_ID=$QUANTUM_NODE_ID
QUANTUM_NODE_IP=$QUANTUM_NODE_IP
EOF
chmod 600 "$QUANTUM_SDN_CONF"

echo "[INFO] Deployment configuration:"
echo "[INFO]   CONTROLLER_HOST = $CONTROLLER_HOST"
echo "[INFO]   QUANTUM_NODE_ID = $QUANTUM_NODE_ID"
echo "[INFO]   QUANTUM_NODE_IP = $QUANTUM_NODE_IP"
echo "[INFO]   Config file     = $QUANTUM_SDN_CONF"
echo

# 0. WSL Systemd Verification, Runtime Directory Permissions & DBus
if grep -qi microsoft /proc/version 2>/dev/null || [ -n "$WSL_DISTRO_NAME" ]; then
    echo "[*] Checking WSL systemd configuration..."
    
    WSL_CONF_MODIFIED=false
    
    if ! grep -iq "systemd=true" /etc/wsl.conf 2>/dev/null; then
        echo "[!] systemd is not enabled in /etc/wsl.conf. Auto-configuring now..."
        if ! grep -q "\[boot\]" /etc/wsl.conf 2>/dev/null; then
            echo -e "\n[boot]\nsystemd=true" | sudo tee -a /etc/wsl.conf >/dev/null
        else
            sudo sed -i '/^\[boot\]/a systemd=true' /etc/wsl.conf
        fi
        WSL_CONF_MODIFIED=true
    fi

    # Check if systemd is actively running as PID 1
    if [ "$(ps -p 1 -o comm=)" != "systemd" ]; then
        echo "=================================================================="
        if [ "$WSL_CONF_MODIFIED" = true ]; then
            echo "[!] CRITICAL: /etc/wsl.conf has been updated to enable systemd."
        else
            echo "[!] CRITICAL: systemd is present in /etc/wsl.conf but NOT active."
        fi
        echo "[!] WSL must be fully restarted from Windows for changes to take effect."
        echo ""
        echo "  Please perform the following steps now:"
        echo "    1. Close this WSL terminal."
        echo "    2. Open Windows PowerShell or Command Prompt."
        echo "    3. Run:  wsl.exe --shutdown"
        echo "    4. Re-open your WSL terminal and rerun this bootstrap script."
        echo "=================================================================="
        exit 1
    else
        echo "  -> systemd is active and running as PID 1."
    fi

    # Ensure root mount propagation is shared for Snap containers in WSL2
    sudo mount --make-rshared / 2>/dev/null || true
    
    # Proactively test and heal Snap mount namespace locks (juju.mnt)
    if command -v juju &>/dev/null; then
        if ! juju version &>/dev/null; then
            echo "[!] Stale Snap mount namespace detected. Self-healing Juju runtime..."
            sudo umount -l /run/snapd/ns/juju.mnt 2>/dev/null || true
            sudo /usr/lib/snapd/snap-discard-ns juju 2>/dev/null || true
            sudo rm -rf /run/snapd/ns/juju* 2>/dev/null || true
            sudo systemctl restart apparmor snapd
            sleep 2
        fi
    fi
fi

export XDG_RUNTIME_DIR="/run/user/$(id -u)"
if [ ! -d "$XDG_RUNTIME_DIR" ]; then
    sudo mkdir -p "$XDG_RUNTIME_DIR"
    sudo chown "$(id -u):$(id -g)" "$XDG_RUNTIME_DIR"
    chmod 700 "$XDG_RUNTIME_DIR"
fi

if [ ! -S "$XDG_RUNTIME_DIR/bus" ]; then
    echo "  -> Initializing DBus session to prevent Snap/Juju timeouts..."
    sudo apt-get update -yqq
    sudo apt-get install -yqq dbus-user-session
    export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
    dbus-daemon --session --address="$DBUS_SESSION_BUS_ADDRESS" --fork 2>/dev/null || true
fi

echo "[*] Verifying system dependencies..."
SYSTEM_DEPS=("libffi-dev" "libyaml-dev" "python3-dev" "python3-setuptools" "python3-wheel" "passwd" "iptables" "apparmor" "apparmor-utils" "util-linux-extra" "openssh-server" "openssh-client")

if ! python3 -c "import ensurepip" &>/dev/null; then
    SYSTEM_DEPS+=("python3-venv")
fi

if ! command -v pip3 &>/dev/null; then
    SYSTEM_DEPS+=("python3-pip")
fi

MISSING_DEPS=()
for pkg in "${SYSTEM_DEPS[@]}"; do
    if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
        MISSING_DEPS+=("$pkg")
    fi
done

if [ ${#MISSING_DEPS[@]} -ne 0 ]; then
    echo "[!] Missing system packages: ${MISSING_DEPS[*]}"
    echo "[*] Installing missing system packages via apt..."
    sudo apt-get update -y
    sudo apt-get install -y "${MISSING_DEPS[@]}"
else
    echo "  -> All required system dependencies are already installed."
fi

# Verify and install gnmic for gNMI benchmark tests (pinned to match the
# controller so both sides agree on flag semantics and output formatting)
GNMIC_VERSION="0.49.0"
if ! command -v gnmic &>/dev/null; then
    echo "[*] Installing gnmic ${GNMIC_VERSION} CLI tool..."
    ARCH=$(uname -m)
    case "$ARCH" in
        x86_64)  GNMIC_ARCH="x86_64"  ;;
        aarch64) GNMIC_ARCH="aarch64" ;;
        *)       GNMIC_ARCH="x86_64"  ;;
    esac
    curl -sSL -o /tmp/gnmic.tar.gz \
        "https://github.com/openconfig/gnmic/releases/download/v${GNMIC_VERSION}/gnmic_${GNMIC_VERSION}_linux_${GNMIC_ARCH}.tar.gz"
    sudo tar xzf /tmp/gnmic.tar.gz -C /usr/local/bin gnmic
    sudo chmod +x /usr/local/bin/gnmic
    rm -f /tmp/gnmic.tar.gz
    echo "  -> gnmic ${GNMIC_VERSION} installed successfully."
else
    INSTALLED_GNMIC=$(gnmic version 2>/dev/null | awk '/version/ {print $NF}')
    if [ "$INSTALLED_GNMIC" != "$GNMIC_VERSION" ]; then
        echo "  -> gnmic is installed (${INSTALLED_GNMIC}) but ${GNMIC_VERSION} is expected."
        echo "     To pin to ${GNMIC_VERSION}: sudo rm /usr/local/bin/gnmic && re-run this script."
    else
        echo "  -> gnmic ${GNMIC_VERSION} is already installed."
    fi
fi

# Verify and install grpcurl for gRPC/onos-topo debugging
if ! command -v grpcurl &>/dev/null; then
    echo "[*] Installing grpcurl CLI tool..."
    curl -sSL https://github.com/fullstorydev/grpcurl/releases/download/v1.9.1/grpcurl_1.9.1_linux_x86_64.tar.gz | sudo tar -xz -C /usr/local/bin grpcurl
    echo "  -> grpcurl installed successfully."
else
    echo "  -> grpcurl is already installed."
fi

# Ensure AppArmor daemon is running on host
sudo systemctl enable --now apparmor 2>/dev/null || true

# 1b. LXD Group Verification & Session Elevation
echo "[*] Verifying LXD installation and group permissions..."
if ! command -v lxd &>/dev/null; then
    echo "  -> Installing LXD via snap..."
    sudo snap install lxd --channel=latest/stable 2>/dev/null || true
fi

if ! id -nG "$USER" | grep -qw "lxd"; then
    echo "  -> Adding $USER to the lxd group..."
    sudo usermod -aG lxd "$USER"
fi

# Elevate current script execution context to include effective group 'lxd'
if ! id -nG | grep -qw "lxd"; then
    echo "  -> Elevating LXD group session and restarting bootstrap process..."
    exec sudo -E -u "$USER" -g lxd stdbuf -oL -eL bash "$0" "$@"
fi

sudo lxd init --auto 2>/dev/null || true

# 2. Local SSH Check for Juju Unmanaged Controller
echo "[*] Verifying local SSH environment..."

if ! command -v sshd &>/dev/null; then
    echo "[!] OpenSSH server is missing."
    echo "    It should have been installed with the system dependencies."
    exit 1
fi

echo "  -> Ensuring SSH daemon is enabled and running..."
sudo systemctl enable --now ssh 2>/dev/null || sudo systemctl enable --now sshd 2>/dev/null || {
    echo "[!] Failed to start the SSH daemon."
    exit 1
}

# Juju controller is bootstrapped directly on the WSL host using the
# unmanaged/manual provider. No LXD or nested virtualization is required.
JUJU_SSH_KEY="$HOME/.ssh/juju_bootstrap_ed25519"
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"

if [ ! -f "$JUJU_SSH_KEY" ]; then
    echo "  -> Creating a dedicated SSH key for the local Juju bootstrap..."
    ssh-keygen -q -t ed25519 -N "" -f "$JUJU_SSH_KEY"
fi

touch "$HOME/.ssh/authorized_keys"
chmod 600 "$HOME/.ssh/authorized_keys"

if ! grep -Fqx "$(cat "${JUJU_SSH_KEY}.pub")" "$HOME/.ssh/authorized_keys" 2>/dev/null; then
    echo "  -> Authorizing the Juju bootstrap SSH key..."
    cat "${JUJU_SSH_KEY}.pub" >> "$HOME/.ssh/authorized_keys"
fi

echo "  -> Configuring SSH for the local Juju bootstrap..."

touch "$HOME/.ssh/config"
chmod 600 "$HOME/.ssh/config"

if ! grep -q "^Host 127\.0\.0\.1$" "$HOME/.ssh/config"; then
    cat >> "$HOME/.ssh/config" <<EOF

Host 127.0.0.1
    User $USER
    IdentityFile $JUJU_SSH_KEY
    IdentitiesOnly yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    ControlMaster no
EOF
fi

echo "  -> Testing local SSH connectivity for Juju..."

if ! ssh -o BatchMode=yes \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o IdentitiesOnly=yes \
        -o ControlMaster=no \
        -i "$JUJU_SSH_KEY" \
        "$USER@127.0.0.1" true >/dev/null 2>&1; then
    echo "[!] Local SSH connectivity test failed."
    echo "    Juju requires SSH access to the WSL host for the unmanaged controller."
    exit 1
fi

echo "  -> Local SSH connectivity is working."
echo "  -> SSH key configured for Juju: $JUJU_SSH_KEY"

# 3. Canonical Juju & Charmcraft Tooling Check / Auto-Install
echo "[*] Verifying Canonical Juju tooling..."

if ! command -v juju &>/dev/null; then
    echo "[!] Juju CLI not found. Installing via snap..."
    
    if ! command -v snap &>/dev/null; then
        echo "[!] Snap package manager not found."
        exit 1
    fi

    sudo systemctl restart snapd
    sleep 3
    
    if ! sudo snap install juju --channel=3/stable; then
        echo "[!] Failed to install Juju via snap."
        exit 1
    fi
fi

echo "  -> Juju CLI: $(juju --version | awk '{print $1}')"

if ! command -v charmcraft &>/dev/null; then
    echo "[!] Charmcraft not found. Installing via snap..."
    if command -v snap &>/dev/null; then
        sudo snap install charmcraft --classic
    fi
else
    echo "  -> Charmcraft is installed: $(charmcraft --version | awk '{print $1}')"
fi

# 4. Juju Controller & Model Provisioning
echo "[*] Verifying Juju Controller..."
CONTROLLER_NAME="terminal-controller"

# The Juju controller runs in an LXD container on the WSL host. The
# built-in "localhost" cloud is used directly; no manual-cloud
# registration is needed.
JUJU_BOOTSTRAP_BASE="ubuntu@24.04"

echo "  -> Juju controller bootstrap mode: LXD (localhost)"

wait_for_juju_controller() {
    local attempts="${1:-30}"
    local i
    for i in $(seq 1 "$attempts"); do
        if timeout 5s juju switch "$CONTROLLER_NAME" &>/dev/null; then
            return 0
        fi
        echo "     [Waiting for Juju controller API... ($i/$attempts)]"
        sleep 2
    done
    return 1
}

if juju controllers 2>/dev/null | grep -q "$CONTROLLER_NAME"; then
    echo "  -> Found local registration for '$CONTROLLER_NAME'."

    if wait_for_juju_controller 30; then
        echo "  -> Juju controller '$CONTROLLER_NAME' is active and reachable."
    else
        echo "[!] Juju controller '$CONTROLLER_NAME' is still unreachable after waiting."
        echo "    The existing controller has NOT been deleted or re-bootstrapped."
        echo "    Check with: juju status"
        echo "              juju debug-log"
        exit 1
    fi
else
    echo "[!] '$CONTROLLER_NAME' is not registered locally."

    echo "  -> No registered controller found; preparing local Juju bootstrap..."
    juju clouds --client --format yaml
    echo "  -> Bootstrapping controller on LXD cloud 'localhost'..."
    echo "     Controller: $CONTROLLER_NAME"
    echo "     Base:       $JUJU_BOOTSTRAP_BASE"
    echo
    juju bootstrap --bootstrap-base="$JUJU_BOOTSTRAP_BASE" localhost "$CONTROLLER_NAME" || {
        echo "[!] Failed to bootstrap Juju controller."
        exit 1
    }
    echo "  -> Juju bootstrap completed successfully."
fi

# The Juju controller runs inside an LXD container on the WSL host.
echo "[*] Verifying Juju controller container..."
if ! lxc list 2>/dev/null | grep -q "juju-"; then
    echo "[!] Juju controller LXD container could not be found."
    exit 1
fi

# Check for and switch to the target model
echo "[*] Verifying Juju Model..."
if ! timeout 5s juju switch "${CONTROLLER_NAME}:terminal-model" &>/dev/null; then
    echo "  -> Creating 'terminal-model'..."
    juju add-model terminal-model -c "$CONTROLLER_NAME" || {
        echo "[!] Failed to create model."
        exit 1
    }
else
    echo "  -> 'terminal-model' is already active and selected."
fi

# 5. Directory Structure Verification
echo "[*] Verifying project structure..."
mkdir -p src/api/proto src/api/yang src/api/grpc src/api/restconf charm scripts config tests

# 6. Virtual Environment Provisioning
VENV_DIR=".venv"
if [ -d "$VENV_DIR" ] && [ ! -f "${VENV_DIR}/bin/pip" ]; then
    echo "[!] Incomplete virtual environment detected. Cleaning up..."
    rm -rf "$VENV_DIR"
fi

if [ ! -d "$VENV_DIR" ]; then
    echo "[*] Creating isolated Python environment in ${VENV_DIR}..."
    python3 -m venv "$VENV_DIR"
else
    echo "[*] Existing environment found in ${VENV_DIR}."
fi

VENV_PYTHON="${VENV_DIR}/bin/python3"
VENV_PIP="${VENV_DIR}/bin/pip"
VENV_PYANG="${VENV_DIR}/bin/pyang"

# 7. Dependency Installation
echo "[*] Upgrading pip and installing dependencies..."
"$VENV_PIP" install --upgrade pip setuptools wheel

if [ -f "requirements.txt" ]; then
    "$VENV_PIP" install -r requirements.txt
else
    "$VENV_PIP" install \
        grpcio \
        grpcio-tools \
        pyang \
        pygnmi \
        gnoi-client \
        onos-api \
        ops \
        fastapi \
        uvicorn \
        pyyaml
fi

# 8. Compile Protobuf Schemas
PROTO_DIR="src/api/proto"
GRPC_OUT_DIR="src/api/grpc"

echo "[*] Compiling gRPC definitions..."
touch "src/__init__.py" "src/api/__init__.py" "${GRPC_OUT_DIR}/__init__.py"

if [ -d "$PROTO_DIR" ] && [ -n "$(ls -A "$PROTO_DIR"/*.proto 2>/dev/null)" ]; then
    for proto_file in "$PROTO_DIR"/*.proto; do
        echo "  -> Compiling ${proto_file}..."
        "$VENV_PYTHON" -m grpc_tools.protoc \
            -I"$PROTO_DIR" \
            --python_out="$GRPC_OUT_DIR" \
            --grpc_python_out="$GRPC_OUT_DIR" \
            "$proto_file"
    done
else
    echo "[!] No .proto files found in ${PROTO_DIR}/. Skipping gRPC compilation."
fi

# 9. Validate YANG Schemas
YANG_DIR="src/api/yang"

echo "[*] Validating YANG models..."
if [ -d "$YANG_DIR" ] && [ -n "$(ls -A "$YANG_DIR"/*.yang 2>/dev/null)" ]; then
    for yang_file in "$YANG_DIR"/*.yang; do
        echo "  -> Validating ${yang_file}..."
        "$VENV_PYANG" "$yang_file"
        "$VENV_PYANG" -f tree "$yang_file" -o "${yang_file%.yang}.tree"
    done
else
    echo "[!] No .yang files found in ${YANG_DIR}/. Skipping YANG validation."
fi

# 10. Apply Execution Permissions & Stubs
echo "[*] Setting execution permissions on scripts..."
chmod +x scripts/*.py 2>/dev/null || true
chmod +x scripts/*.sh 2>/dev/null || true
chmod +x tests/*.sh 2>/dev/null || true

# =============================================================================
# 10b. Generate OpenConfig gNMI stubs for direct-gRPC clients
#
# tests/test-sdn-protocol-switching-performance.sh uses a direct-gRPC gNMI
# client (tests/gnmi_daemon.py) that imports gnmi_pb2 and gnmi_pb2_grpc.
# Those stubs must be generated from the OpenConfig gNMI proto files. We pin
# the same v0.9.1 revision the controller repo uses so both sides agree on
# the message definitions.
# =============================================================================
echo "[*] Generating OpenConfig gNMI stubs..."

GNMI_PROTO_DIR="proto"
GNMI_EXT_DIR="${GNMI_PROTO_DIR}/github.com/openconfig/gnmi/proto/gnmi_ext"

mkdir -p "$GNMI_EXT_DIR"

if [ ! -f "${GNMI_PROTO_DIR}/gnmi.proto" ]; then
    echo "  -> Downloading gnmi.proto (v0.9.1)..."
    curl -fsSL \
        https://raw.githubusercontent.com/openconfig/gnmi/v0.9.1/proto/gnmi/gnmi.proto \
        -o "${GNMI_PROTO_DIR}/gnmi.proto"
fi

if [ ! -f "${GNMI_EXT_DIR}/gnmi_ext.proto" ]; then
    echo "  -> Downloading gnmi_ext.proto (v0.9.1)..."
    curl -fsSL \
        https://raw.githubusercontent.com/openconfig/gnmi/v0.9.1/proto/gnmi_ext/gnmi_ext.proto \
        -o "${GNMI_EXT_DIR}/gnmi_ext.proto"
fi

echo "  -> Compiling gNMI protobuf stubs..."
"$VENV_PYTHON" -m grpc_tools.protoc \
    -I"${GNMI_PROTO_DIR}" \
    --python_out="${GNMI_PROTO_DIR}" \
    --grpc_python_out="${GNMI_PROTO_DIR}" \
    "${GNMI_PROTO_DIR}/gnmi.proto" \
    "${GNMI_EXT_DIR}/gnmi_ext.proto"

# Python package markers for the nested extension path
touch "${GNMI_PROTO_DIR}/__init__.py"
for d in github github/com github/com/openconfig github/com/openconfig/gnmi \
         github/com/openconfig/gnmi/proto github/com/openconfig/gnmi/proto/gnmi_ext; do
    mkdir -p "${GNMI_PROTO_DIR}/$d"
    touch "${GNMI_PROTO_DIR}/$d/__init__.py"
done

echo "    [OK] gNMI stubs generated in ${GNMI_PROTO_DIR}/"

# =============================================================================
# 11. Final Persistence / Reboot Safety Verification
# =============================================================================
echo "[*] Verifying reboot/power-cycle persistence..."

# The Juju controller runs inside an LXD container. Verify that systemd is
# active and that the controller container is present.
SYSTEMD_ACTIVE=false
if [ "$(ps -p 1 -o comm=)" = "systemd" ]; then
    SYSTEMD_ACTIVE=true
fi

JUJU_SERVICE_FOUND=false
if lxc list 2>/dev/null | grep -q "juju-"; then
    JUJU_SERVICE_FOUND=true
fi

echo "  -> WSL systemd active: $SYSTEMD_ACTIVE"
echo "  -> Juju controller service found: $JUJU_SERVICE_FOUND"
echo "  -> Juju controller: $CONTROLLER_NAME"

echo "=================================================================="
echo "[+] Bootstrap complete! System and local environment ready."
echo "[+] Optional Juju tests available in ./tests/"
echo -e "To view your pods and juju services, run:"
echo -e "  juju status --watch 5s"
echo "=================================================================="
